In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf

"""
Everything in TensorFlow is based on Tensor operations.
Tensors are (kind of) like np.arrays.
All tensors are immutable: you can never update the contents of a
tensor, only create a new one.
 - nd-arrays (1d, 2d, or even 3d and higher)
 - GPU support
 - Computational graph / Track gradients / Backpropagation
 - Immutable!
"""

'\nEverything in TensorFlow is based on Tensor operations.\nTensors are (kind of) like np.arrays.\nAll tensors are immutable: you can never update the contents of a\ntensor, only create a new one.\n - nd-arrays (1d, 2d, or even 3d and higher)\n - GPU support\n - Computational graph / Track gradients / Backpropagation\n - Immutable!\n'

In [4]:
# 1. create tensors
# scalar, rank-0 tensor
x = tf.constant(4)
print(x)

x = tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)

# vector, rank-1
x = tf.constant([1,2,3])
print(x)

# matrix, rank-2
x = tf.constant([[1,2,3], [4,5,6]])
print(x)

x = tf.ones((3,3))
print(x)

x = tf.zeros((3,3))
print(x)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [5]:
x = tf.eye(3)
print(x)

x = tf.random.normal((3,3), mean=0, stddev=1)
print(x)

x = tf.random.uniform((3,3), minval=0, maxval=1)
print(x)

x = tf.range(10)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-0.24629726 -0.4945614   1.0835437 ]
 [ 0.43170157 -0.33546293 -0.4515872 ]
 [-1.1103983  -0.64850724  0.08757156]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.40589035 0.18058944 0.16275525]
 [0.85937655 0.13868523 0.06075001]
 [0.7165849  0.643697   0.6493621 ]], shape=(3, 3), dtype=float32)
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [6]:
# 2. cast:
x = tf.cast(x, dtype=tf.float32)
print(x)

tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)


In [9]:
# 3. operations, elementwise
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

z = tf.add(x, y)
print(z)
z = x + y
print(z)

z = tf.subtract(x,y)
print(z)
z = x - y
print(z)

z = tf.divide(x,y)
print(z)
z = x / y
print(z)

z = tf.multiply(x,y)
print(z)
z = x * y
print(z)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)
tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [15]:
# dot product
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

z = tf.tensordot(x,y, axes=1)
print(z)

# elementwise exponentiate
z = x ** 3
print(z)

# matrix multiplication (shapes must match: number of columns A = number of rows B)
x = tf.random.normal((2,3)) # 2,3
y = tf.random.normal((3,4)) # 3,4

z = tf.matmul(x,y)
print(z)
z = x @ y
print(z)

tf.Tensor(32, shape=(), dtype=int32)
tf.Tensor([ 1  8 27], shape=(3,), dtype=int32)
tf.Tensor(
[[ 0.4614767   0.55926204 -0.78394705  0.26001382]
 [-0.35201377  1.3811787  -1.9914672   4.062103  ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 0.4614767   0.55926204 -0.78394705  0.26001382]
 [-0.35201377  1.3811787  -1.9914672   4.062103  ]], shape=(2, 4), dtype=float32)


In [16]:
# 4. indexing, slicing
x = tf.constant([[1,2,3,4],[5,6,7,8]])
print(x[0])
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([1 5], shape=(2,), dtype=int32)
tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [22]:
# 5. reshape
x = tf.random.normal((2,3))
print(x)
x = tf.reshape(x, (3,2))
print(x)

x = tf.reshape(x, (-1,2))
print(x)

x = tf.reshape(x, (6))
print(x)

tf.Tensor(
[[-1.9579849  -0.4596213   0.02820609]
 [-0.9118685   0.34856138  1.8066748 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[-1.9579849  -0.4596213 ]
 [ 0.02820609 -0.9118685 ]
 [ 0.34856138  1.8066748 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[-1.9579849  -0.4596213 ]
 [ 0.02820609 -0.9118685 ]
 [ 0.34856138  1.8066748 ]], shape=(3, 2), dtype=float32)
tf.Tensor([-1.9579849  -0.4596213   0.02820609 -0.9118685   0.34856138  1.8066748 ], shape=(6,), dtype=float32)


In [23]:
# 6. numpy
x = x.numpy()
print(type(x))

x = tf.convert_to_tensor(x)
print(type(x))
# -> eager tensor = evaluates operations immediately
# without building graphs

# string tensor
x = tf.constant("Patrick")
print(x)

x = tf.constant(["Patrick", "Max", "Mary"])
print(x)

# Variable
# A tf.Variable represents a tensor whose value can be
# changed by running ops on it
# Used to represent shared, persistent state your program manipulates
# Higher level libraries like tf.keras use tf.Variable to store model parameters.
b = tf.Variable([[1.0, 2.0, 3.0]])
print(b)
print(type(b))

<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(b'Patrick', shape=(), dtype=string)
tf.Tensor([b'Patrick' b'Max' b'Mary'], shape=(3,), dtype=string)
<tf.Variable 'Variable:0' shape=(1, 3) dtype=float32, numpy=array([[1., 2., 3.]], dtype=float32)>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
