In [2]:
# First Neural Net
# Train, evaluate, and predict with the model
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [3]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

mnist = keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape, y_train.shape)

(60000, 28, 28) (60000,)


In [5]:
# normalize: 0,255 -> 0,1
x_train, x_test = x_train / 255.0, x_test / 255.0

# model
model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=(28,28)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(10),
])

print(model.summary())

# another way to build the Sequential model:
#model = keras.models.Sequential()
#model.add(keras.layers.Flatten(input_shape=(28,28))
#model.add(keras.layers.Dense(128, activation='relu'))
#model.add(keras.layers.Dense(10))

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 784)               0         
                                                                 
 dense_2 (Dense)             (None, 128)               100480    
                                                                 
 dense_3 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________
None


In [7]:
# loss and optimizer

loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True)
optim = keras.optimizers.Adam(learning_rate=0.001)
metrics = ["accuracy"]

model.compile(loss=loss, optimizer=optim, metrics=metrics)

In [9]:
# training
batch_size = 64
epochs = 5

model.fit(x_train, y_train, batch_size = batch_size, epochs = epochs, shuffle = True, verbose=2)

Epoch 1/5
938/938 - 1s - loss: 0.3279 - accuracy: 0.9069 - 1s/epoch - 1ms/step
Epoch 2/5
938/938 - 1s - loss: 0.3134 - accuracy: 0.9105 - 1s/epoch - 1ms/step
Epoch 3/5
938/938 - 1s - loss: 0.3021 - accuracy: 0.9138 - 1s/epoch - 1ms/step
Epoch 4/5
938/938 - 1s - loss: 0.2925 - accuracy: 0.9159 - 1s/epoch - 1ms/step
Epoch 5/5
938/938 - 1s - loss: 0.2846 - accuracy: 0.9182 - 1s/epoch - 1ms/step


In [10]:
# evaluate
model.evaluate(x_test, y_test, batch_size = batch_size, verbose = 2)

157/157 - 0s - loss: 0.2737 - accuracy: 0.9226 - 286ms/epoch - 2ms/step


[0.27367186546325684, 0.9225999712944031]

In [11]:
# predictions

# 1. option: build new model with Softmax layer
probability_model = keras.models.Sequential([
    model, 
    keras.layers.Softmax()
])

predictions = probability_model(x_test)
pred0 = predictions[0]
print(pred0)

# use np.argmax to get label with highest probability
label0 = np.argmax(pred0)
print(label0)

tf.Tensor(
[7.7841818e-05 1.7397545e-08 9.5210940e-05 1.6074878e-03 5.9363515e-07
 3.8044425e-05 5.5559561e-09 9.9720287e-01 1.2846308e-05 9.6509903e-04], shape=(10,), dtype=float32)
7


In [12]:
# 2. option: original model + nn.softmax, call model(x)
predictions = model(x_test)
predictions = tf.nn.softmax(predictions)
pred0 = predictions[0]
print(pred0)
label0 = np.argmax(pred0)
print(label0)

tf.Tensor(
[7.7841818e-05 1.7397545e-08 9.5210940e-05 1.6074878e-03 5.9363515e-07
 3.8044425e-05 5.5559561e-09 9.9720287e-01 1.2846308e-05 9.6509903e-04], shape=(10,), dtype=float32)
7


In [13]:
# 3. option: original model + nn.softmax, call model.predict(x)
predictions = model.predict(x_test, batch_size=batch_size)
predictions = tf.nn.softmax(predictions)
pred0 = predictions[0]
print(pred0)
label0 = np.argmax(pred0)
print(label0)

tf.Tensor(
[7.7841745e-05 1.7397545e-08 9.5210846e-05 1.6074878e-03 5.9363515e-07
 3.8044425e-05 5.5559455e-09 9.9720287e-01 1.2846308e-05 9.6509862e-04], shape=(10,), dtype=float32)
7


In [14]:
# call argmax for multiple labels
pred05s = predictions[0:5]
print(pred05s.shape)
label05s = np.argmax(pred05s, axis=1)
print(label05s)

(5, 10)
[7 2 1 0 4]
