# TensorFlow tutorial

video list in youtube: https://www.youtube.com/watch?v=o0Upa0yrbS0&list=PLEtcGQaT56chOBjdO10AbBwnx1Acuj3Hu
https://www.tensorflow.org/learn

## Tutorial 1

In [1]:
import tensorflow as tf

print('tensorflow version ', tf.__version__)

x=[[3.]]
y=[[4.]]

print('result: {}'.format(tf.matmul(x,y)))

hola = tf.constant("Hola Mundo")
tf.print(hola)

tensorflow version  2.5.0
result: [[12.]]
Hola Mundo


## Tipos de variables

Tensores de orden 0, 1 ,2, 3

In [5]:
# Tensores Rango 0, variables

mammal = tf.Variable("Elephant", tf.string)
ignition = tf.Variable(451,tf.int16)
floating = tf.Variable(3.14159, tf.float64)
its_complicated = tf.Variable(12.3 - 4.85j, tf.complex64)

# Tensores rango 1, vectores
myStr = tf.Variable(["Hello"], tf.string)
cool_numbers = tf.Variable([3.14159, 2.71828],tf.float32)
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32)
its_very_complicated = tf.Variable([12.3 - 4.85j, 7.5 - 6.23j], tf.complex64)

# Tensores rango 2 o superior, Matrices, contienen almenos una fila y una columna
myMat = tf.Variable([[7],[11]],tf.int16)
myxor = tf.Variable([[False, True],[True, False]],tf.bool)
linear_square = tf.Variable([[4],[9],[16],[25]],tf.int32)
squarish_square = tf.Variable([[4, 9],[16, 25]],tf.int32)
rank_of_squares = tf.rank(squarish_square)
myMatC = tf.Variable([[7],[11]], tf.int32)

# Tensores de rango superior
my_image = tf.zeros([10, 299, 299, 3]) # batch x height x width x color
r = tf.rank(my_image)
tf.print(r)

4


## Tutorial 3

In [20]:
t1 = tf.constant([1.5, 2.5, 3.5])
tf.print(t1)

t2 = tf.constant([['c','c'], ['c','c']])
tf.print(t2)

t3 = tf.zeros([5])
tf.print(t3)

t4 = tf.ones([5,4])
tf.print(t4)

t5= tf.fill([3,4,3],2)
tf.print(t5)

t6= tf.linspace(5,9,5)
tf.print(t6)

t7 = tf.range(5,21,3)
tf.print(t7)

[1.5 2.5 3.5]
[["c" "c"]
 ["c" "c"]]
[0 0 0 0 0]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[[2 2 2]
  [2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]
  [2 2 2]]]
[5 6 7 8 9]
[5 8 11 14 17 20]


## Tutorial 8

In [23]:
# Valores aleatorios

valores_aleatorios = tf.random.normal([10], dtype=tf.float64)
tf.print(valores_aleatorios)

# reshape
vector = tf.constant([1.,2.,3.,4.])
matriz = tf.reshape(vector, [2,2])
tf.print(matriz)

#aplicar un slice
matriz = tf.constant([[1.,2.,3.], [4.,5.,6.],[7.,8.,9.]])
sliceMatriz = tf.slice(matriz, [1,1], [2,2])
tf.print(sliceMatriz)

#operadores
a = tf.constant([3.,3.,3.])
b = tf.constant([2.,2.,2.])

suma = tf.add(a,b)
resta = tf.subtract(b,a)
mult = tf.multiply(a,b)
divi = tf.divide(b,a)

tf.print(suma)
tf.print(resta)
tf.print(mult)
tf.print(divi)

[-0.67284737391311089 -0.091035772142918622 0.063116382396244439 ... -0.90025135393876132 0.51749279539321624 -0.10601461165018736]
[[1 2]
 [3 4]]
[[5 6]
 [8 9]]
[5 5 5]
[-1 -1 -1]
[6 6 6]
[0.666666687 0.666666687 0.666666687]


## Tutorial 2

In [ ]:
tfs = tf.compat.v1
tfs.disable_eager_execution()

# Crear Tensor
mensaje = tfs.string_join(["Hola ", "Mundo"])

# lanzar mensaje
with tfs.Session() as sess:
    print(sess.run(mensaje))